### PR TITLE
Allows users to optionally set kagi.com as their default new tab page (new tab page override etc)

### PR DESCRIPTION
**Pull request by con-dog**
## What it does
Adds the ability for a user to optionally set kagi.com as their default new tab page, toggling the setting via a checkbox in the popup panel

## Why ?
Improves the UX flow of using Kagi as your default search engine. By always opening a new tab to Kagi.com, a user gets a better search experience. Additionally the "Assistants" are more readily accessible via kagi.com

## Implementation Details
- Added checkbox to popup panel to toggle this option on/off (defaults to off)
- Added 2 new required permissions to manifest (storage, tabs)
  - Storage permission required to store users choice across browser sessions
  - Tabs permission required to listen for creation of chrome://newtab/ and conditionally perform override
- Touches "service_worker.js" to perform the override, and new files "popup.js", "redirect.js", "new-tab.html"

## Testing
- Tested on Chrome Version 131.0.6778.109 (Official Build) (arm64)
- Verified that:
  - New tab override works when enabled
  - Setting persists across browser sessions
  - Setting can be toggled on/off
  - Original new tab behaviour remains when disabled
  
## Reasons against merging
- The normal way to add a new tab page is to override the chrome default new tab. However doing this would opt every Kagi extension user into a new tab experience (bad!)
- To make the new tab experience optional, the only way is to use the tabs permission (listen to tab activations) combined with storage permission (perform action based on stored setting.

## Screenshots
Screenshot 2024-12-09 at 8 10 02 PM

### CODE REVIEW

**Comment by con-dog** [comment]
Hello Kagi team, just checking in :) any chance this would be merged? I’m rocking it locally currently with no issues! 

Also wondering if you have any other extensions planned in the future, how about a sidepanel extension for chrome for a global search panel? Would love to contribute more 

Thank you,
Papillon

**Comment by PixeLInc** [comment]
Hi there @con-dog, sorry for the wait.

This looks fine, but one thing that I would rather we not do is use the "tabs" permission, at least not as a 'default' permission.

We previously had this permission set on our extensions and it was not received well (https://github.com/kagisearch/browser_extensions/issues/13) & (https://github.com/kagisearch/browser_extensions/issues/17)

There is an `optional_permissions` field in the manifest which I think we should rather use.
https://developer.chrome.com/docs/extensions/reference/api/permissions

This makes it so that it requires an explicit user confirmation that they *want* to enable this permission and doesn't always require it and it doesn't show up in the "permissions" section of the extension.

We use this optional permissions in our other repository which hosts the firefox (and old chrome) extension, for `activeTab`, you can give that a look and see how that works if you're interested. ([link](https://github.com/kagisearch/browser_extensions/))
The above chrome dev docs also have an example on there of doing an optional 'tabs' permission too.

Does that make sense & sound good to you?

**Comment by con-dog** [comment]
Hi @PixeLInc no problem :) Good call on it not being received well. I will play around with optional_permissions for both storage and tabs.

Sounds really good to me, I will post an update tomorrow :)

Cheers,
Papillon

**Comment by con-dog** [comment]
Have made those changes @PixeLInc , managed to get it down to just 1 optional_permission "tabs"

**Comment by PixeLInc** [comment]
Hey there @con-dog,

Unfortunately after looking into it further, it appears that this feature actually is explicitly *not allowed* as per chrome store guidelines...

img

https://developer.chrome.com/docs/webstore/program-policies/api-use	

If we were to want to do this, we'd have to always override the new tab page with a markup file and redirect from there (which is how other extensions that do this do it), but at that point it becomes not optional and more complicated (and also, that feels a little dodgy too).

So! Due to that, unfortunately we can't add this as to not break those rules.
(our extension has already been removed once for a fairly minor thing - best not push our luck)

Sorry about all that, I did not realize this was the case originally otherwise I would've mentioned it right away.
Thank you for doing submitting the feature regardless, though!

**Comment by con-dog** [comment]
Hey @PixeLInc no worries, thats a shame that chrome don't allow this functionality. I agree an alternative approach would be too hacky to implement, and its not worth the risk of getting taken down.

**Pull request closed without merging**
